This analysis requires the whole simulation (signalcesuperlong2) to already have been minimized. The dataframe with all of the minimized autos is loaded

In [1]:
import pandas as pd
import numpy as np
import copy
import random
from __future__ import division
from __future__ import with_statement
import platform
import datetime
import minimization as minz #My script in same folder for minimization routines

In [2]:
#Import epochs file (thesis folder)
epochs = pd.read_csv("/Users/luisalejandrolee/Dropbox/Thesis Phd/\
Coordination autos Chapter three/outputs_from_python/\
epochs_av_signalcesuperlong2_states_8_signal_1_rounds_50_N_40_parents_20.txt")
epochs = epochs.drop('Unnamed: 0',1) #Organise
epochs = epochs.rename(columns={"epoch":"regime"})

#Import Minimized individual machines (thesis folder)
autos = pd.read_csv("/Users/luisalejandrolee/Dropbox/Thesis Phd/\
Coordination autos Chapter three/outputs_from_python/\
individual_machines_signalcesuperlong2_states_8_signal_1_rounds_50_N_40_parents_20.txt")
autos = autos.drop('Unnamed: 0',1)#Organise

#Import summary (desktop folder)
summary = pd.read_csv("/Users/luisalejandrolee/Desktop/outputs_from_netlogo/\
summary_signalcesuperlong2_states_8_signal_1_rounds_50_N_40_parents_20.txt")

#1) Add CEM to epochs dataframe
First, we create a new column into the epochs dataframe containing the average CEM (correlated equilibrium measure) for each particular epoch.

In [67]:
#Create a list with the average CEM for each regime in epochs
cem = [] #empty list
for i in epochs.index: #all epochs
    start = int(epochs.start[i])
    end = int(epochs.end[i])
    my_list = summary.ce[start:end] #required ce values

    ce = sum(my_list)/len(my_list) #get the average of my_list
    cem.append(ce)

#add cem averages to epochs dataframe
epochs['cem'] = cem

Then I observe the epochs by regime, in order to check visually which epochs to keep for the analysis

In [78]:
epochs[epochs.regime=='Domination_AA']

           regime  duration  start    end       cem
6   Domination_AA       178  28476  28654  0.001988
8   Domination_AA        22  28790  28812  0.002914
10  Domination_AA      2514  28865  31379  0.001432
12  Domination_AA      3623  31981  35604  0.001364
17  Domination_AA      4405  54220  58625  0.002224
19  Domination_AA      1267  59581  60848  0.001364
21  Domination_AA       829  66190  67019  0.000636
23  Domination_AA       832  67582  68414  0.000584
28  Domination_AA      1023  87298  88321  0.006810
30  Domination_AA      2170  88945  91115  0.000976
32  Domination_AA      1762  92140  93902  0.001473

In [70]:
epochs[epochs.regime=='Turn_Taking']

         regime  duration  start    end       cem
18  Turn_Taking       936  58637  59573  0.124782
20  Turn_Taking      5326  60856  66182  0.125341
25  Turn_Taking      7336  70877  78213  0.884996
27  Turn_Taking      8733  78556  87289  0.853684

In [75]:
epochs[(epochs.regime=='Biased_Turn_A') | (epochs.regime=='Biased_Turn_B')]

           regime  duration  start     end       cem
4   Biased_Turn_A     25617   2774   28391  0.112274
14  Biased_Turn_B      2762  37080   39842  0.233776
16  Biased_Turn_B      9590  44621   54211  0.405229
34  Biased_Turn_A      4936  95064  100000  0.401399

#2) Choose the epochs to analyse

1) From Domination I only need one epochs (since they all have CEM=0). Choose index=19 (has few generations)

2) From Turn-Taking,just keep two with different CEM (choose index = 18, 25)

3) From Biased, keep two with different CEM (index = 14, 16)

So based on the above, keep epochs 19, 18, 25, 14 and 16.

In [85]:
list_of_epochs = [19,18,25,14,16]
epochs = epochs[epochs.index.isin(list_of_epochs)] #choose only selected rows
epochs

           regime  duration  start    end       cem
14  Biased_Turn_B      2762  37080  39842  0.233776
16  Biased_Turn_B      9590  44621  54211  0.405229
18    Turn_Taking       936  58637  59573  0.124782
19  Domination_AA      1267  59581  60848  0.001364
25    Turn_Taking      7336  70877  78213  0.884996

### The process now is to choose for each epoch the top machines

The code is copied over and over for each epoch just for easy of analysis (a loop would only allow printing which is visually less engaging)

#Domination_A (CEM=0.00)

In [154]:
i = 19 #epoch to analyse (based on index of epochs dataframe)
n_top_machines = 10 #rows to show of the top machines

start = int(epochs.start[i])
end = int(epochs.end[i])

n_pop = 40*(end-start) #autos per population in the whole epoch
autosep = autos[(autos.generation >= start) & (autos.generation <= end)] #autos in the epoch
    
g1 = autosep.groupby([autosep['min_autos'], autosep['population']]) #group by machines and populations

g1 = g1.count().drop([' ce_individual','score'],1) #drop some columns
g1 = g1.rename(columns={"generation":"percentage"}) #rename

g1['percentage'] = [(x*100)/n_pop for x in g1.percentage] #calculate percentage of machine in the epoch
g1.sort('percentage',ascending=False)[:n_top_machines] #show sorted

                                                               percentage
min_autos                                          population
[('A', [0, 0, 0, 0])]                              column        2.158642
[('A', [1, 3, 3, 3]) ('A', [2, 3, 2, 0]) ('A', ... row           2.034333
[('A', [1, 2, 0, 3]) ('A', [0, 0, 0, 1]) ('B', ... column        1.391081
[('A', [1, 4, 4, 4]) ('A', [2, 4, 2, 3]) ('A', ... row           1.347672
[('A', [1, 2, 0, 1]) ('A', [2, 0, 2, 2]) ('A', ... column        1.207577
[('A', [1, 3, 6, 3]) ('A', [2, 3, 6, 2]) ('A', ... row           1.189818
[('A', [1, 3, 3, 3]) ('A', [2, 3, 2, 0]) ('A', ... row           1.118785
[('A', [1, 2, 0, 5]) ('A', [0, 0, 2, 1]) ('A', ... column        1.085241
[('A', [1, 2, 0, 4]) ('A', [0, 0, 0, 1]) ('B', ... column        1.085241
[('A', [1, 2, 0, 4]) ('A', [0, 0, 0, 1]) ('B', ... column        1.065509

# Turn_Taking (CEM=0.12)

In [155]:
i = 18 #epoch to analyse (based on index of epochs dataframe)
n_top_machines = 15 #rows to show of the top machines

start = int(epochs.start[i])
end = int(epochs.end[i])

n_pop = 40*(end-start) #autos per population in the whole epoch
autosep = autos[(autos.generation >= start) & (autos.generation <= end)] #autos in the epoch
    
g1 = autosep.groupby([autosep['min_autos'], autosep['population']]) #group by machines and populations

g1 = g1.count().drop([' ce_individual','score'],1) #drop some columns
g1 = g1.rename(columns={"generation":"percentage"}) #rename

g1['percentage'] = [(x*100)/n_pop for x in g1.percentage] #calculate percentage of machine in the epoch
g1.sort('percentage',ascending=False)[:n_top_machines] #show sorted

                                                               percentage
min_autos                                          population
[('B', [0, 1, 5, 4]) ('A', [2, 5, 2, 6]) ('B', ... row           2.828526
[('A', [1, 2, 4, 4]) ('B', [2, 3, 2, 5]) ('A', ... row           2.662927
[('B', [0, 1, 3, 4]) ('A', [2, 6, 2, 5]) ('B', ... row           2.091346
[('A', [1, 1, 4, 1]) ('B', [2, 3, 2, 3]) ('A', ... row           1.995192
[('A', [1, 2, 4, 4]) ('B', [2, 3, 2, 5]) ('A', ... row           1.984509
[('B', [0, 1, 3, 2]) ('A', [2, 6, 2, 5]) ('B', ... row           1.941774
[('B', [0, 1, 0, 6]) ('B', [1, 2, 5, 2]) ('A', ... row           1.442308
[('A', [1, 0, 1, 1]) ('B', [2, 2, 5, 2]) ('A', ... column        1.420940
[('A', [1, 6, 1, 4]) ('B', [2, 2, 4, 2]) ('A', ... column        1.356838
[('B', [0, 1, 3, 4]) ('A', [2, 6, 2, 5]) ('B', ... row           1.252671
[('B', [0, 1, 2, 2]) ('A', [2, 6, 2, 4]) ('B', ... row           1.177885
[('B', [0, 1, 3, 4]) ('A', [2, 6, 2, 5]) ('B', ... row           1.177885
[('B', [1, 4, 0, 6]) ('B', [2, 2, 3, 2]) ('A', ... column        1.177885
[('B', [0, 1, 3, 4]) ('A', [2, 6, 2, 5]) ('B', ... row           1.113782
[('A', [1, 4, 1, 7]) ('B', [2, 2, 7, 2]) ('A', ... column        1.063034

# Turn_Taking (CEM=0.88)

In [156]:
i = 25 #epoch to analyse (based on index of epochs dataframe)
n_top_machines = 10 #rows to show of the top machines

start = int(epochs.start[i])
end = int(epochs.end[i])

n_pop = 40*(end-start) #autos per population in the whole epoch
autosep = autos[(autos.generation >= start) & (autos.generation <= end)] #autos in the epoch
    
g1 = autosep.groupby([autosep['min_autos'], autosep['population']]) #group by machines and populations

g1 = g1.count().drop([' ce_individual','score'],1) #drop some columns
g1 = g1.rename(columns={"generation":"percentage"}) #rename

g1['percentage'] = [(x*100)/n_pop for x in g1.percentage] #calculate percentage of machine in the epoch
g1.sort('percentage',ascending=False)[:n_top_machines] #show sorted

                                                               percentage
min_autos                                          population
[('A', [1, 1, 0, 1]) ('B', [0, 1, 0, 0])]          row           2.090376
[('A', [1, 3, 0, 3]) ('B', [2, 1, 4, 4]) ('A', ... row           1.079948
[('A', [0, 1, 0, 3]) ('A', [2, 1, 1, 3]) ('B', ... column        1.072451
[('A', [1, 1, 0, 1]) ('B', [2, 1, 2, 0]) ('A', ... row           1.013154
[('A', [0, 1, 0, 3]) ('A', [2, 3, 1, 4]) ('B', ... column        0.765403
[('A', [1, 3, 0, 5]) ('B', [2, 1, 4, 4]) ('A', ... row           0.639995
[('A', [0, 1, 0, 3]) ('A', [2, 1, 1, 3]) ('B', ... column        0.631134
[('A', [1, 3, 0, 3]) ('B', [0, 1, 2, 0]) ('A', ... row           0.599100
[('A', [1, 1, 0, 1]) ('B', [2, 1, 4, 0]) ('A', ... row           0.502658
[('A', [0, 1, 0, 6]) ('A', [2, 3, 1, 3]) ('B', ... column        0.493457

#Biased_Turn_B (CEM=0.23)

In [157]:
i = 14 #epoch to analyse (based on index of epochs dataframe)
n_top_machines = 15 #rows to show of the top machines

start = int(epochs.start[i])
end = int(epochs.end[i])

n_pop = 40*(end-start) #autos per population in the whole epoch
autosep = autos[(autos.generation >= start) & (autos.generation <= end)] #autos in the epoch
    
g1 = autosep.groupby([autosep['min_autos'], autosep['population']]) #group by machines and populations

g1 = g1.count().drop([' ce_individual','score'],1) #drop some columns
g1 = g1.rename(columns={"generation":"percentage"}) #rename

g1['percentage'] = [(x*100)/n_pop for x in g1.percentage] #calculate percentage of machine in the epoch
g1.sort('percentage',ascending=False)[:n_top_machines] #show sorted

                                                               percentage
min_autos                                          population
[('B', [1, 1, 1, 0]) ('A', [2, 1, 0, 1]) ('B', ... column       68.587980
[('B', [1, 0, 5, 0]) ('A', [2, 1, 4, 0]) ('B', ... row           3.569877
[('B', [1, 0, 3, 0]) ('A', [2, 1, 4, 0]) ('B', ... row           3.437726
[('B', [1, 0, 1, 0]) ('A', [2, 1, 4, 0]) ('B', ... row           3.044895
[('B', [1, 0, 4, 0]) ('A', [2, 1, 5, 0]) ('B', ... row           2.309015
[('B', [1, 0, 5, 0]) ('A', [2, 1, 4, 0]) ('B', ... row           2.071868
[('B', [1, 0, 3, 0]) ('A', [2, 1, 4, 0]) ('B', ... row           1.809377
[('B', [1, 0, 1, 0]) ('A', [2, 1, 4, 0]) ('B', ... row           1.687183
[('B', [1, 0, 1, 0]) ('A', [2, 1, 6, 0]) ('B', ... row           1.661839
[('B', [1, 0, 5, 0]) ('A', [2, 1, 6, 2]) ('B', ... row           1.567705
[('B', [1, 1, 1, 0]) ('A', [2, 1, 0, 1]) ('B', ... column        1.450941
[('B', [1, 0, 4, 6]) ('A', [2, 1, 5, 0]) ('B', ... row           1.331463
[('B', [0, 0, 0, 0])]                              column        1.256336
[('A', [1, 1, 1, 0]) ('A', [2, 1, 0, 1]) ('B', ... column        1.197502
[('B', [1, 0, 1, 0]) ('A', [2, 1, 6, 0]) ('B', ... row           1.184830

#Biased_Turn_B (CEM=0.40)

In [158]:
i = 16 #epoch to analyse (based on index of epochs dataframe)
n_top_machines = 15 #rows to show of the top machines

start = int(epochs.start[i])
end = int(epochs.end[i])

n_pop = 40*(end-start) #autos per population in the whole epoch
autosep = autos[(autos.generation >= start) & (autos.generation <= end)] #autos in the epoch
    
g1 = autosep.groupby([autosep['min_autos'], autosep['population']]) #group by machines and populations

g1 = g1.count().drop([' ce_individual','score'],1) #drop some columns
g1 = g1.rename(columns={"generation":"percentage"}) #rename

g1['percentage'] = [(x*100)/n_pop for x in g1.percentage] #calculate percentage of machine in the epoch
g1.sort('percentage',ascending=False)[:n_top_machines] #show sorted

                                                               percentage
min_autos                                          population
[('B', [1, 2, 1, 1]) ('A', [2, 1, 2, 3]) ('B', ... row           3.979666
[('B', [1, 0, 2, 3]) ('A', [2, 3, 2, 1]) ('B', ... row           2.651721
[('A', [1, 5, 4, 5]) ('B', [2, 1, 3, 0]) ('A', ... column        1.256257
[('B', [0, 0, 1, 3]) ('B', [0, 1, 1, 2]) ('A', ... row           1.108446
[('A', [1, 1, 1, 1]) ('B', [0, 1, 0, 0])]          column        1.080553
[('B', [1, 0, 2, 3]) ('A', [2, 3, 2, 1]) ('B', ... row           1.033368
[('B', [0, 0, 0, 1]) ('A', [0, 0, 2, 5]) ('B', ... row           0.993222
[('A', [1, 5, 4, 5]) ('B', [2, 1, 3, 0]) ('A', ... column        0.958029
[('B', [1, 0, 2, 3]) ('A', [2, 3, 2, 1]) ('B', ... row           0.866267
[('B', [1, 0, 3, 3]) ('A', [2, 3, 2, 1]) ('B', ... row           0.770334
[('B', [1, 0, 3, 3]) ('A', [2, 3, 2, 1]) ('B', ... row           0.770073
[('B', [1, 0, 0, 2]) ('B', [2, 0, 4, 0]) ('A', ... row           0.636340
[('B', [1, 2, 3, 3]) ('B', [2, 1, 1, 3]) ('B', ... row           0.617049
[('B', [1, 1, 3, 3]) ('B', [0, 2, 1, 2]) ('B', ... row           0.601147
[('B', [1, 2, 4, 4]) ('B', [0, 2, 1, 2]) ('B', ... row           0.571689

In [143]:
start = 75000
end = 75000

n_pop = 40*(1) #autos per population in the whole epoch
autosep = autos[(autos.generation >= start) & (autos.generation <= end)] #autos in the epoch
    
g1 = autosep.groupby([autosep['min_autos'], autosep['population']]) #group by machines and populations

g1 = g1.count().drop([' ce_individual','score'],1) #drop some columns
g1 = g1.rename(columns={"generation":"percentage"}) #rename

g1['percentage'] = [(x*100)/n_pop for x in g1.percentage] #calculate percentage of machine in the epoch
g1.sort('percentage',ascending=False)[:n_top_machines] #show sorted

                                                               percentage
min_autos                                          population
[('B', [1, 3, 4, 4]) ('B', [2, 5, 0, 4]) ('B', ... row               62.5
[('A', [0, 1, 0, 3]) ('A', [2, 4, 3, 6]) ('B', ... column            32.5
[('A', [0, 1, 0, 3]) ('A', [2, 4, 3, 6]) ('B', ... column            10.0
[('B', [1, 1, 4, 4]) ('A', [2, 5, 0, 4]) ('B', ... row                7.5
[('A', [0, 1, 0, 3]) ('A', [2, 4, 3, 6]) ('B', ... column             7.5
[('A', [0, 1, 0, 3]) ('A', [2, 4, 5, 6]) ('B', ... column             7.5
[('B', [1, 3, 4, 4]) ('B', [2, 5, 0, 4]) ('B', ... row                5.0
[('B', [1, 3, 4, 4]) ('B', [2, 5, 0, 4]) ('B', ... row                5.0
[('A', [1, 3, 4, 4]) ('B', [2, 5, 0, 4]) ('B', ... row                5.0
[('A', [0, 1, 0, 1]) ('A', [2, 3, 1, 3]) ('B', ... column             5.0
[('B', [1, 3, 4, 4]) ('B', [2, 5, 0, 4]) ('B', ... row                2.5
[('B', [1, 3, 4, 4]) ('B', [2, 5, 0, 4]) ('B', ... row                2.5
[('A', [0, 1, 0, 4]) ('A', [2, 5, 4, 3]) ('B', ... column             2.5
[('B', [1, 3, 4, 4]) ('B', [2, 5, 0, 4]) ('B', ... row                2.5
[('B', [1, 3, 4, 4]) ('A', [2, 5, 0, 4]) ('B', ... row                2.5

In [144]:
sum(g1.percentage)

200.0

#Miscelaneous: average payoffs by population

In [12]:
print 'Signal payoffs:'
print 'Row average payoffs: ', summary.av_score_row.mean()
print 'Column average payoffs: ', summary.av_score_col.mean()

Signal payoffs:
Row average payoffs:  2.37342206587
Column average payoffs:  2.43502455537

In [10]:
summary_ns = pd.read_csv("/Users/luisalejandrolee/Desktop/outputs_from_netlogo/\
summary_nosignalsuperlong2_states_8_signal_0_rounds_50_N_40_parents_20.txt")

In [14]:
print 'NO Signal payoffs:'
print 'Row average payoffs: ', summary_ns.av_score_row.mean()
print 'Column average payoffs: ', summary_ns.av_score_col.mean()

NO Signal payoffs:
Row average payoffs:  2.25946448612
Column average payoffs:  2.484583162